#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d 一 二 三 四 五 六 七 八 九 十

background=$(xrdb -query | grep "background" | cut -f2 | sed -r 's/#//' | head -n 1)
foreground=$(xrdb -query | grep "foreground" | cut -f2 | sed -r 's/#//' | head -n 1)
color0=$(xrdb -query | grep "color0" | cut -f2 | sed -r 's/#//' | head -n 1)
color1=$(xrdb -query | grep "color1" | cut -f2 | sed -r 's/#//' | head -n 1)
color2=$(xrdb -query | grep "color2" | cut -f2 | sed -r 's/#//' | head -n 1)
color3=$(xrdb -query | grep "color3" | cut -f2 | sed -r 's/#//' | head -n 1)
color4=$(xrdb -query | grep "color4" | cut -f2 | sed -r 's/#//' | head -n 1)
color5=$(xrdb -query | grep "color5" | cut -f2 | sed -r 's/#//' | head -n 1)
color6=$(xrdb -query | grep "color6" | cut -f2 | sed -r 's/#//' | head -n 1)
color7=$(xrdb -query | grep "color7" | cut -f2 | sed -r 's/#//' | head -n 1)
color8=$(xrdb -query | grep "color8" | cut -f2 | sed -r 's/#//' | head -n 1)


bspc config border_width         2
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config focus_follows_pointer true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a firefox desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

# Autostart
xsetroot -cursor_name left_ptr &
polybar -c ~/.config/bspwm/polybar/config.ini &
feh --bg-center '/home/dreaming/Pictures/Pics/35.jpg' &
#lxappearance &
#xfce4-power-manager &
#xfce4-power-manager-settings & 